= Encoding of Swath Data in the Climate and Forecast Convention
:toc: preamble
:toclevels: 4
:icons: font

====
This is a proposal for an extension of the http://cfconventions.org[Climate and Forecast metadata convention].

The work is done under the U.S. National Science Foundation award https://www.nsf.gov/awardsearch/showAward?AWD_ID=1541031[1541031]: +
"EarthCube IA: Advancing netCDF-CF for the Geoscience Community".

Proposal status: *[red]#DRAFT#*.

Last modified: 2017-01-23
====

== Introduction

Earth Science swath data are collected by an instrument that observes a smaller portion of Earth at any given instant while its platform (an object carrying such instrument) moves and the instrument sweeps over a wider area of Earth. Usually, successive swath observations are combined to cover a larger portion of Earth, sometimes even the entire Earth. When these successive observations are plotted on maps they appear to cover a swath on the Earth's surface, hence the name.

Swath data originates as measurements of electromagnetic radiation at a number of intervals of the electromagnetic spectrum, called _bands_ or _channels_. These radiometric swath data are commonly referred to as _Level 1_. Further processing these data to retrieve geophysical parameters produces so-called _Level 2_ swath data.

The aim of this proposal is to standardize encodings of both radiometric (Level 1) and geophysical (Level 2) swath data in the Climate and Forecast (CF) convention. The proposed encodings are independent from the observation method and should be applicable to swath data acquired either from satellites, airplanes, or unmanned aerial systems.

The basis for this proposal is the CF convention http://cfconventions.org/cf-conventions/cf-conventions.html[version 1.7] (currently in draft) although backward compatibility with it is not necessarily an objective. Since there are already swath data in netCDF files, the community-provided examples were valuable resource in preparing this proposal. These examples are stored in a GitHub repository at https://github.com/diwg/diwg.

== Swath Data Encodings

The proposed encodings reflect the variety of swath data from the radiometric (for Level 1 data) and geophysical (for Level 2 data) domains. The chief differences between the two domain encodings are:

* Spectral (band, channel) coordinates must be present for all radiometric swath data.
* Geospatial extent for radiometric swath data is always two-dimensional (area), while for geophysical swath data it can also be three-dimensional.
* Geophysical swath data may use coordinates that represent altitude.

All the swath encodings rely on the use of the `featureType` attribute as a variable attribute. This attribute holds the swath encoding type identifier. Currently this requirement breaks the backward compatibility with the CF version 1 conventions. However, the convention's version 1.7 draft http://cfconventions.org/cf-conventions/cf-conventions.html#_features_and_feature_types[allows] for the possibility the `featureType` attribute may become a variable attribute at some later time.

Encoding examples are expressed using the http://www.unidata.ucar.edu/software/netcdf/netcdf/CDL-Syntax.html#CDL-Syntax[NetCDF Common Data Language] (CDL) with only the relevant file content to illustrate the concept.

=== Swath Coordinate

The swath coordinate describes the swath characteristics (e.g., cross-track, conical scan, reprojected to fixed grid) and mapping to geolocation (latitude/longitude for every _n_-th pixel). Other specifications include: coordinate reference (geodetic or geocentric; planetodetic, planetocentric for other planetary bodies) and a fill value (when the swath is off-planet). The slowest varying dimension of the geolocation coordinate must represent forward (along-track) movement of the platform.

[caption="Example 0: "]
.Geolocation array for MODIS (starts at 3,3 and sampled 5x5).
====
----
  group: MODIS_SWATH_Type_L1B {
    dimensions:
      2*nscans = 406;
      1KM_geo_dim = 271;
    variables:
      int 10*nscans(2*nscans=406);
        :_DimensionMap = "";

      int Max_EV_frames(1KM_geo_dim=271);
        :_DimensionMap = "";


    group: Geolocation_Fields {
      variables:
        float Latitude(2*nscans=406, 1KM_geo_dim=271);
          :units = "degrees_north";
          :valid_range = -90.0f, 90.0f; // float
          :_FillValue = -999.0f; // float
          :line_numbers = "3,8";
          :frame_numbers = "3,8,13,...";
          :_CoordinateAxisType = "Lat";

        float Longitude(2*nscans=406, 1KM_geo_dim=271);
          :units = "degrees_east";
          :valid_range = -180.0f, 180.0f; // float
          :_FillValue = -999.0f; // float
          :line_numbers = "3,8";
          :frame_numbers = "3,8,13,...";
          :_CoordinateAxisType = "Lon";

    }
----

====

=== Time Coordinate

Specifying the time coordinate for swath data follows the pertinent CF convention rules. The rank of the time coordinate can range from one (one-dimensional) up to the rank of the swath data variable to which it applies (2, 3, ..., _n_-dimensional). The slowest varying dimension of the coordinate must represent forward (along-track) movement of the platform.

[caption="Example 1: "]
.Time coordinate.
====
----
dimensions:
  time = 10 ; <1>

variables:
    double time(time) ;
      time:standard_name = "time" ;
      time:units = "<units> since <datetime string>" ;
      time:calendar = "gregorian" ;
----
<1> The dimension represents the forward (along track) platform movement. It can also be an unlimited dimension (`time = UNLIMITED`).
====

TIP: Time coordinates with rank greater than one must be listed in the `coordinates` attribute of their swath data variables.

Some satellite swath data use the International Atomic Time (TAI) which currently is not supported by the CF convention (see this http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2015/058061.html[thread] on the CF mailing list for background). The encoding examples in this proposal use the Gregorian calendar.

=== Spectral Coordinate

Specifying bands (channels) is done with spectral coordinates. Band information can either be numerical (e.g., wavelength, wavenumber, or frequency) or character (contained in a string).

[caption="Example 2: "]
.Numerical spectral coordinate.
====
----
dimensions:
  band = 5 ; <1>

variables:
  float band(band) ; <2>
    band:standard_name = "sensor_band_central_radiation_wavelength" ; <3>
    band:units = "μm" ;
----
<1> Number of bands.
<2> The `band` variable is a coordinate variable.
<3> One of the standard names specifically for numerical band data. The other two names are `sensor_band_central_radiation_wavenumber` and `sensor_band_central_radiation_frequency`.
====

String band information is applicable to cases where bands cannot be differentiated solely numerically, for example, when polarization together with electromagnetic spectrum interval definition has to be combined.

[caption="Example 3: "]
.String band coordinate.
====
For the netCDF classic model:
----
dimensions:
  band_enum = 5 ; <1>
  band_strlen = 10 ; <2>

variables:
  char band(band_enum, band_strlen) ;
    band:standard_name = "sensor_band_identifier" ; <3>
----
<1> Number of bands.
<2> Number of characters of the longest band string identifier.
<3> The standard name specifically for band string identifiers.

For the netCDF extended model (strongly recommended to use):
----
dimensions:
  band_enum = 5 ;

variables:
  string band(band_enum) ;
     band:standard_name = "sensor_band_identifier" ;
----
====

=== Radiometric Swath Domain Encodings

==== Multiband

Multiband swath data are the most common radiometric swath data, collected over an area on the Earth as successive across-track observations at a number of different bands.

[caption="Example 4: "]
.Multiband data with numerical spectral coordinate.
====
----
dimensions:
  time = 120 ;
  scan = 512 ;
  band = 8 ;

variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "μm" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, band) ;
    swath_data:featureType = "multibandSwath" ;
    swath_data:coordinates = "lon lat" ;
----
====

Another encoding of the Multiband Swath with string-valued band coordinate because numerical band information may not always be sufficient.

[caption="Example 5: "]
.Multiband data with string spectral coordinate.
====
----
dimensions:
  time = UNLIMITED ;
  scan = 1024 ;
  band_enum = 8 ;

variables:
  string band(band_enum) ;
    band:standard_name = "sensor_band_identifier" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, band_enum) ;
    swath_data:featureType = "multibandSwath" ;
    swath_data:coordinates = "lon lat band" ;
----
====

==== Multiband with Field-of-View Shape

Along with the multiband swath data itself, sometimes it may be required to specify the shape of each field-of-view (FOV). The Multiband Swath encoding is extended with additional variables to define field-of-view geospatial extent.

[WARNING]
====
This encoding example is under review and may change in the future.
====

[caption="Example 6: "]
.Multiband data with field-of-view shapes.
====
----
dimensions:
  time = 10 ;
  scan = 512 ;
  band = 5 ;
  waypoints = 4 ;

variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "μm" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;
    lat:bounds = "lat_bounds" ;

  float lat_bounds(time, scan, waypoints) ;
    lat_bounds:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;
    lon:bounds = "lon_bounds" ;

  float lon_bounds(time, scan, waypoints) ;
    lon_bounds:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, band) ;
    swath_data:featureType = "multibandSwath" ;
    swath_data:coordinates = "lon lat" ;
----
====

==== Multiband Image

So far the presented encodings are for swath data collected by successive across-track observations. Two-dimensional imaging sensors, such as in digital cameras, can acquire swath data as a multiband image.

[caption="Example 7: "]
.Multiband Image data.
====
----
dimensions:
  time = 1 ;
  nrows = 2048 ; <1>
  ncols = 2048 ; <2>
  band = 10 ;

variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "μm" ;

  float lat(time, nrows, ncols) ;
     lat:standard_name = "latitude" ;
     lat:units = "degrees_north" ;

  float lon(time, nrows, ncols) ;
     lon:standard_name = "longitude" ;
     lon:units = "degrees_east" ;

  double time(time) ;
     time:standard_name = "time" ;
     time:units = "<units> since <datetime string>" ;
     time:calendar = "gregorian" ;

  float swath_data(time, nrows, ncols, band) ;
     swath_data:featureType = "multibandImageSwath" ;
     swath_data:coordinates = "lon lat" ;
----
<1> Number of rows of the two-dimensional imaging sensor.
<2> Number of columns of the two-dimensional imaging sensor.
====

The same encoding is also applicable to swath data from hyperspectral sounding instruments which make observations with their detectors arranged into a grid, typically 2-by-2 or 3-by-3. Such grouping of the field-of-views is referred to as a field-of-regard (FOR). The following example is identical to the previous one except for two dimensions with changed names.

[caption="Example 8: "]
.Multiband Image data for each field-of-regard/field-of-view.
====
----
dimensions:
  time = 50 ;
  FOR = 45 ; <1>
  FOV = 9 ; <2>
  band = 1305 ;

variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "μm" ;

  short FOV(FOV); <3>
    FOV:long_name = "Field-of-view ordinal number" ;

  float lat(time, FOR, FOV) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, FOR, FOV) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, FOR, FOV, band) ;
    swath_data:featureType = "multibandImageSwath" ;
    swath_data:coordinates = "lon lat" ;
----
<1> The number of field-of-regards in one across-track scan.
<2> The number of field-of-views within one field-of-regard.
<3> This variable can be left out if there is no need to define a particular ordering of field-of-views within the field-of-regard.
====

An interesting variation in the above encoding would be if the `FOR` and `FOV` dimensions exchanged places in the ordering, e.g. `(time, FOR, FOV, ...)` -> `(time, FOV, FOR, ...)`. The latter ordering corresponds to the spatial arrangement of the FORs and FOVs: FORs match the columns and FOVs match the rows of a two-dimensional imaging sensor. In other words: `FOR` -> `ncols` and `FOV` -> `nrows`.

==== Multiband Field-of-Regard with Field-of-View Shapes

This is an extension on the Multiband Image feature type when the geospatial extent of all field-of-views in each field-of-regard need to be provided.

[WARNING]
====
This encoding example is under review and may change in the future.
====

[caption="Example 9: "]
.title
====
----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  FOR = 30 ;
  band = 1305 ;
  FOV = 9 ;
  waypoints = 8 ;


variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "μm" ;

  float lat(time, FOR, FOV) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;
    lat:bounds = "lat_bounds" ;

  float lat_bounds(time, FOR, FOV, waypoints) ;
    lat_bounds:units = "degrees_north" ;

  float lon(time, FOR, FOV) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;
    lon:bounds = "lon_bounds" ;

  float lon_bounds(time, FOR, FOV, waypoints) ;
    lon_bounds:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, FOR, FOV, band) ;
    swath_data:featureType = "multiBandForSwath" ;
    swath_data:coordinates = "lon lat" ;
----
====

=== Geophysical Swath Domain Encodings

==== Swath

[caption="Example 10: "]
.Swath data.
====
----
dimensions:
  time = 512 ;
  scan = 1024 ;

variables:
  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  float swath_data(time, scan) ;
    swath_data:featureType = "swath" ;
    swath_data:coordinates = "lon lat" ;
----
====

For completeness, the example below uses along- and across-track dimensions.

[caption="Example 11: "]
.Swath data utilizing along- and across-track dimensions.
====
----
dimensions:
  atrack = 512 ;
  xtrack = 1024 ;

variables:
  double time(atrack) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float lat(atrack, xtrack) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(atrack, xtrack) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  float swath_data(atrack, xtrack) ;
    swath_data:featureType = "swath" ;
    swath_data:coordinates = "time lon lat" ;
----
====

==== Image Swath

This is the geophysical analog of the Multiband Image Swath feature type.

[caption="Example 12: "]
.Image Swath data.
====
----
dimensions:
  time = 1 ;
  nrows = 1024 ;
  ncols = 3600 ;

variables:
  float lat(time, nrows, ncols) ;
     lat:standard_name = "latitude" ;
     lat:units = "degrees_north" ;

  float lon(time, nrows, ncols) ;
     lon:standard_name = "longitude" ;
     lon:units = "degrees_east" ;

  double time(time) ;
     time:standard_name = "time" ;
     time:units = "<units> since <datetime string>" ;
     time:calendar = "gregorian" ;

  float swath_data(time, nrows, ncols) ;
     swath_data:featureType = "imageSwath" ;
     swath_data:coordinates = "lon lat" ;
----
====

[caption="Example 13: "]
.The version of this feature type for each field-of-regard/field-of-view.
====
----
dimensions:
  time = UNLIMITED ;
  FOR = 30 ;
  FOV = 9 ;

variables:
  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float lat(time, FOR, FOV) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, FOR, FOV) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  float swath_data(time, FOR, FOV) ;
    swath_data:featureType = "imageSwath" ;
    swath_data:coordinates = "lon lat" ;
----
====

==== Profile

This feature type consists of the Swath with an altitude coordinate. All types of altitude coordinates are allowed.

[caption="Example 14: "]
.Profile data.
====
----
dimensions:
  time = UNLIMITED ;
  scan = 512 ;
  press = 15 ;


variables:
  float press(press) ;
    press:standard_name = "air_pressure" ;
    press:units = "Pa" ;
    press:positive = "up" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, press) ;
    swath_data:featureType = "profileSwath" ;
    swath_data:coordinates = "lon lat" ;
----
====

[caption="Example 15: "]
.Profile data utilizing along- and across-track dimensions.
====
----
dimensions:
  atrack = 512 ;
  xtrack = 1024 ;
  press = 15 ;

variables:
float press(press) ;
  press:standard_name = "air_pressure" ;
  press:units = "Pa" ;
  press:positive = "up" ;

  double time(atrack) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float lat(atrack, xtrack) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(atrack, xtrack) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  float swath_data(atrack, xtrack, pres) ;
    swath_data:featureType = "profileSwath" ;
    swath_data:coordinates = "time lon lat" ;
----
====

==== Multiband Profile

[caption="Example 16: "]
.Multiband Profile data.
====
----
dimensions:
  time = UNLIMITED ;
  scan = 512 ;
  band = 5 ;
  press = 15 ;

variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavenumber" ;
    band:units = "cm-1" ;

  float press(press) ;
    press:standard_name = "air_pressure" ;
    press:units = "Pa" ;
    press:positive = "up" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, press, band) ;
    swath_data:featureType = "multibandProfileSwath" ;
    swath_data:coordinates = "lon lat" ;
----
====

==== Image Profile

Adding an altitude coordinate to the Image Swath feature type makes this one.

[caption="Example 17: "]
.Image Profile data.
====
----
dimensions:
  time = 1 ;
  nrows = 1024 ;
  ncols = 3600 ;
  pres = 100 ;

variables:
float press(press) ;
  press:standard_name = "air_pressure" ;
  press:units = "Pa" ;
  press:positive = "up" ;

  float lat(time, nrows, ncols) ;
     lat:standard_name = "latitude" ;
     lat:units = "degrees_north" ;

  float lon(time, nrows, ncols) ;
     lon:standard_name = "longitude" ;
     lon:units = "degrees_east" ;

  double time(time) ;
     time:standard_name = "time" ;
     time:units = "<units> since <datetime string>" ;
     time:calendar = "gregorian" ;

  float swath_data(time, nrows, ncols, pres) ;
     swath_data:featureType = "imageProfileSwath" ;
     swath_data:coordinates = "lon lat" ;
----
====

As in the few previous encoding examples, assuming that `nrows` represents field-of-regards and `ncols` represents field-of-views, this feature type can be used for storing profiles from hyperspectral sounders for each field-of-view.

==== Field-of-Regard Profile

There are two more ways how to encode swath data from field-of-views and field-of-regards. The differing features of these encodings are:

* How much latitude/longitude data is provided: for all field-of-views in each field-of-regard, or just for each field-of-regard as a whole.
* A two-dimensional layout of field-of-views within the field-of-regard.

[caption="Example 18: "]
.Field-of-Regard Profile data with latitude and longitude data for all field-of-views in each field-of-regard.
====
----
dimensions:
  time = 10 ;
  FOR = 30 ; <1>
  press = 15 ;
  FOV_atrack = 3 ; <2>
  FOV_xtrack = 3 ; <3>

variables:
  float press(press) ;
    press:standard_name = "air_pressure" ;
    press:units = "Pa" ;
    press:positive = "up" ;

  float lat(time, FOR, FOV_atrack, FOV_xtrack) ; <4>
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, FOR, FOV_atrack, FOV_xtrack) ; <4>
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, FOR, FOV_atrack, FOV_xtrack, press) ;
    swath_data:featureType = "FORProfileSwath" ;
    swath_data:coordinates = "lon lat" ;
----
<1> Number of field-of-regards in one across-track scan.
<2> Along-track (_row_) dimension of the field-of-view _matrix_.
<3> Across-track (_column_) dimension of the field-of-view _matrix_.
<4> Latitude and longitude for all field-of-views in the field-of-regard.
====

[caption="Example 19: "]
.Field-of-Regard Profile data with latitude and longitude data for each field-of-regard as a whole.
====
----
dimensions:
  time = 10 ;
  FOR = 30 ;
  press = 15 ;
  FOV_atrack = 3 ;
  FOV_xtrack = 3 ;

variables:
  short FOV_atrack(FOV_atrack): <1>
    FOV_atrack:long_name = "Field-of-view along track ordinal number" ;

  short FOV_xtrack(FOV_xtrack): <1>
    FOV_xtrack:long_name = "Field-of-view across track ordinal number" ;

  float press(press) ;
    press:standard_name = "air_pressure" ;
    press:units = "Pa" ;
    press:positive = "up" ;

  float lat(time, FOR) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, FOR) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, FOR, FOV_atrack, FOV_xtrack, press) ;
    swath_data:featureType = "FORProfileSwath" ;
    swath_data:coordinates = "lon lat" ;
----
<1> `FOV_atrack` and `FOV_xtrack` are coordinates now compared to the previous example because the `lat` and `lon` auxiliary coordinates do not depend on them.
====
