= Encoding of Swath Data in the Climate and Forecast Convention
:toc:
:toclevels: 4
:icons: font

[NOTE]
====
This is a draft proposal for an extension of the Climate and Forecast metadata convention developed under the U.S. National Science Foundation award 1541031: "EarthCube IA: Advancing netCDF-CF for the Geoscience Community".
====

== Introduction

Earth Science swath data are collected by an instrument that observes a smaller portion of Earth at any given instant while its platform (an object carrying such instrument) moves and the instrument sweeps over a wider area of Earth. Usually, successive swath observations are combined to cover a larger portion of Earth, sometimes even the entire Earth. When these successive observations are plotted on maps they appear to cover a swath on the Earth's surface, hence the name.

Swath data originates as measurements of electromagnetic radiation at a number of intervals of the electromagnetic spectrum, called _bands_ or _channels_. These radiometric swath data are commonly referred to as _Level 1_. Further processing these data to retrieve geophysical parameters produces so-called _Level 2_ swath data.

The aim of this proposal is to standardize encodings of both radiometric (Level 1) and geophysical (Level 2) swath data in the Climate and Forecast (CF) convention. The proposed encodings are independent from the observation method and should be applicable to swath data acquired either from satellites, airplanes, or unmanned aerial systems.

The basis for this proposal is the CF convention http://cfconventions.org/cf-conventions/cf-conventions.html[version 1.7] (currently in draft) although backward compatibility with it is not necessarily an objective. Since there are already swath data in netCDF files, the community-provided examples were valuable resource in preparing this proposal. These examples are stored in a GitHub repository at https://github.com/diwg/diwg.

== Swath Data Encodings

The proposed encodings reflect the variety of swath data from the radiometric (for Level 1 data) and geophysical (for Level 2 data) domains. The chief differences between the two domain encodings are:

* Spectral (band, channel) coordinates must be present for all radiometric swath data.
* Geospatial extent for radiometric swath data is always two-dimensional (area), while for geophysical swath data it can also be three-dimensional.
* Geophysical swath data may use coordinates that represent altitude.

All the swath encodings rely on the use of the `featureType` attribute as a variable attribute. This attribute holds the swath encoding type identifier. Currently this requirement breaks the backward compatibility with the CF version 1 conventions. However, the convention's version 1.7 draft http://cfconventions.org/cf-conventions/cf-conventions.html#_features_and_feature_types[allows] for the possibility the `featureType` attribute may become a variable attribute at some later time.

Encoding examples are expressed using the http://www.unidata.ucar.edu/software/netcdf/netcdf/CDL-Syntax.html#CDL-Syntax[NetCDF Common Data Language] (CDL) with only the relevant file content to illustrate the concept.

=== Time Coordinate

Specifying time coordinate for swath data follows the pertinent CF convention rules. The rank of the time coordinate can range from one (one-dimensional) up to the rank of the swath data variable to which it applies (2, 3, ..., _n_-dimensional). The slowest varying dimension of the coordinate must represent forward (along-track) movement of the platform.

Some satellite swath data use the International Atomic Time (TAI) which currently is not supported by the CF convention (see this http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2015/058061.html[thread] on the CF mailing list for background). The encoding examples in this proposal use the Gregorian calendar.

=== Spectral Coordinate

Specifying bands (channels) is done with spectral coordinates. Band information can either be numerical (as wavelength, wavenumber, or frequency) or string.

[caption="Example 1: "]
.Numerical spectral coordinate.
====
----
dimensions:
  band = 5 ; <1>

variables:
  float band(band) ; <2>
    band:standard_name = "sensor_band_central_radiation_wavelength" ; <3>
    band:units = "um" ;
----
<1> Number of bands.
<2> The `band` variable is a coordinate variable.
<3> One of standard names specifically for numerical band data. The other two names are `sensor_band_central_radiation_wavenumber` and `sensor_band_central_radiation_frequency`.
====

String band information is applicable to cases where bands cannot be differentiated solely numerically, for example, when polarization together with electromagnetic spectrum interval definition has to be combined.

[caption="Example 2: "]
.String band coordinate.
====
For the netCDF classic model:
----
dimensions:
  band_enum = 5 ; <1>
  band_strlen = 10 ; <2>

variables:
  char band(band_enum, band_strlen) ;
    band:standard_name = "sensor_band_identifier" ; <3>
----
<1> Number of bands.
<2> Number of characters of the longest band string identifier.
<3> The standard name specifically for string band data.

For the netCDF extended model (strongly recommended):
----
dimensions:
  band_enum = 5 ;

variables:
  string band(band_enum) ;
     band:standard_name = "sensor_band_identifier" ;
----

====

=== Radiometric Domain Encodings

==== Multi-Band

This type of data represents probably the most commonly collected swath data, where observations over an area on the Earth are made at a number of different bands (or channels).

----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  scan = 512 ;
  band = 5 ;

variables:
  // spectral coordinate variable
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "um" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, band) ;
    swath_data:featureType = "multiBandSwath" ;
    swath_data:coordinates = "lon lat" ;
----

==== Multi-Band with String Band Information

This is a variation on the Multi-Band Swath where the band information is given as strings because expressing them numerically may not be always appropriate.

----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  scan = 1024 ;
  band_enum = 5 ;
  band_strlen = 10 ;

variables:
  // string-valued auxiliary coordinate variable
  char band(band_enum, band_strlen) ;
    band:standard_name = "sensor_band_identifier" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, band_enum) ;
    swath_data:featureType = "multiStringBandSwath" ;
    swath_data:coordinates = "lon lat band" ;
----

==== Multi-Band with Field-of-View Shape

Along with the swath data itself, sometimes it may be required to specify the shape of the each field-of-view (FOV). The Multi-Band Swath encoding is extended with additional variables for describing the field-of-view geospatial extent.

----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  scan = 512 ;
  band = 5 ;
  waypoints = 4 ;

variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "um" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;
    lat:bounds = "lat_bounds" ;

  float lat_bounds(time, scan, waypoints) ;
    lat_bounds:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;
    lon:bounds = "lon_bounds" ;

  float lon_bounds(time, scan, waypoints) ;
    lon_bounds:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, band) ;
    swath_data:featureType = "multiBandSwath" ;
    swath_data:coordinates = "lon lat" ;
----

==== Multi-Band Field-of-Regard

Hyperspectral sounding instruments typically take observations with their detectors arranged into a 2-by-2 or 3-by-3 grid. Such grouping of the field-of-views is referred to as a field-of-regard (FOR).

----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  for = 45 ;
  band = 1305 ;
  fov = 9 ;

variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "um" ;

  short fov(fov);
    fov:long_name = "Field-of-view ordinal number" ;

  float lat(time, for, fov) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, for, fov) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, for, fov, band) ;
    swath_data:featureType = "multiBandForSwath" ;
    swath_data:coordinates = "lon lat" ;
----

==== Multi-Band Field-of-Regard with Field-of-View Shapes

This is an extension on the Multi-Band Field-of-Regard feature type when geospatial extent of all field-of-views in each field-of-regard need to be specified.

----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  for = 30 ;
  band = 1305 ;
  fov = 9 ;
  waypoints = 8 ;


variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "um" ;

  float lat(time, for, fov) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;
    lat:bounds = "lat_bounds" ;

  float lat_bounds(time, for, fov, waypoints) ;
    lat_bounds:units = "degrees_north" ;

  float lon(time, for, fov) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;
    lon:bounds = "lon_bounds" ;

  float lon_bounds(time, for, fov, waypoints) ;
    lon_bounds:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, for, fov, band) ;
    swath_data:featureType = "multiBandForSwath" ;
    swath_data:coordinates = "lon lat" ;
----

=== Geophysical Domain Encodings

==== Swath

----
dimensions:
  time = 512 ;
  scan = 1024 ;


variables:
  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  float swath_data(time, scan) ;
    swath_data:featureType = "swath" ;
    swath_data:coordinates = "lon lat" ;
----

==== Field-of-Regard Swath

A variant of the Swath feature type, enabling storing data values for all field-of-views of each field-of-regard.

----
dimensions:
  time = 512 ;
  for = 30 ;
  fov = 9 ;


variables:
  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float lat(time, for, fov) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, for, fov) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  float swath_data(time, for, fov) ;
    swath_data:featureType = "swath" ;
    swath_data:coordinates = "lon lat" ;
----

==== Profile

----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  scan = 512 ;
  press = 15 ;


variables:
  float press(press) ;
    press:standard_name = "air_pressure" ;
    press:units = "Pa" ;
    press:positive = "up" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, press) ;
    swath_data:featureType = "profileSwath" ;
    swath_data:coordinates = "lon lat" ;
----

==== Multi-Band Profile

----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  scan = 512 ;
  band = 5 ;
  press = 15 ;


variables:
  float band(band) ;
    band:standard_name = "sensor_band_central_radiation_wavelength" ;
    band:units = "um" ;

  float press(press) ;
    press:standard_name = "air_pressure" ;
    press:units = "Pa" ;
    press:positive = "up" ;

  float lat(time, scan) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, scan) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, scan, press, band) ;
    swath_data:featureType = "multiBandProfileSwath" ;
    swath_data:coordinates = "lon lat" ;
----

==== Field-of-Regard Profile

A variant of the Profile feature type for providing profile data for all field-of-views in each field-of-regard.

----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  for = 30 ;
  press = 15 ;
  fov_atrack = 3 ;
  fov_xtrack = 3 ;


variables:
  float press(press) ;
    press:standard_name = "air_pressure" ;
    press:units = "Pa" ;
    press:positive = "up" ;

  float lat(time, for, fov_atrack, fov_xtrack) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, for, fov_atrack, fov_xtrack) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, for, fov_atrack, fov_xtrack, press) ;
    swath_data:featureType = "forProfileSwath" ;
    swath_data:coordinates = "lon lat" ;
----

Variant #2:

----
dimensions:
  time = 10 ; // option: time = UNLIMITED
  for = 45 ;
  press = 15 ;
  fov = 9 ;


variables:
  float press(press) ;
    press:standard_name = "air_pressure" ;
    press:units = "Pa" ;
    press:positive = "up" ;

  float lat(time, for, fov) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, for, fov) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, for, fov, press) ;
    swath_data:featureType = "forProfileSwath" ;
    swath_data:coordinates = "lon lat" ;
----

Variant #3:

----
dimensions:
  time = 10 ;
  for = 30 ;
  press = 15 ;
  fov_atrack = 3 ;
  fov_xtrack = 3 ;


variables:
  short fov_atrack(fov_atrack):
    fov_atrack:long_name = "Field-of-view along track ordinal number" ;

  short fov_xtrack(fov_xtrack):
    fov_xtrack:long_name = "Field-of-view across track ordinal number" ;

  float press(press) ;
    press:standard_name = "air_pressure" ;
    press:units = "Pa" ;
    press:positive = "up" ;

  float lat(time, for) ;
    lat:standard_name = "latitude" ;
    lat:units = "degrees_north" ;

  float lon(time, for) ;
    lon:standard_name = "longitude" ;
    lon:units = "degrees_east" ;

  double time(time) ;
    time:standard_name = "time" ;
    time:units = "<units> since <datetime string>" ;
    time:calendar = "gregorian" ;

  float swath_data(time, for, fov_atrack, fov_xtrack, press) ;
    swath_data:featureType = "forProfileSwath" ;
    swath_data:coordinates = "lon lat" ;
----
